StoreFront.UI.MVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StoreFront.DATA.EF.Models;
using System.Drawing;
using StoreFront.UI.MVC.Utilities;
using X.PagedList;

namespace StoreFront.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]

    public class ProductsController : Controller
    {
        private readonly EducatedMoneyContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductsController(EducatedMoneyContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Products
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {

            //var product = _context.Products.Include(p => p.Category).Include(p => p.Location);
            if (User.IsInRole("Admin"))
            {
                var product = _context.Products.Include(p => p.Category).Include(p => p.Location);

                return View(await product.ToListAsync());
            }
            else
            {

                var product = _context.Products.Where(p => !p.Discontinued)
                    .Include(p => p.Category)
                    .Include(p => p.Location);


                return View(await product.ToListAsync());
            }
        }

        //GET: Products/TableView
        [AllowAnonymous]
        public async Task<IActionResult> TableView()
        {
            if (User.IsInRole("Admin"))
            {
                var product = _context.Products.Include(p => p.Category).Include(p => p.Location);

                return View(await product.ToListAsync());
            }
            else
            {

                var product = _context.Products.Where(p => !p.Discontinued)
                    .Include(p => p.Category)
                    .Include(p => p.Location);


                return View(await product.ToListAsync());
            }

        }
        [AllowAnonymous]
        public async Task<IActionResult> HomePage()
        {

            if (User.IsInRole("Admin"))
            {
                var product = _context.Products.Include(p => p.Category).Include(p => p.Location);

                return View(await product.ToListAsync());
            }
            else
            {

                var product = _context.Products.Where(p => !p.Discontinued)
                    .Include(p => p.Category)
                    .Include(p => p.Location);



                return View(await product.ToListAsync());

            }

        }

        // GET: Products/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Location)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            ViewData["LocationId"] = new SelectList(_context.ClassLocations, "LocationId", "CampusName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Price,Discontinued,Description,ProductImage,ProductName,CategoryId,LocationId,IsOnline,Image")] Product product)
        {

            if (ModelState.IsValid)
            {


                if (product.Image != null)
                {

                    string ext = Path.GetExtension(product.Image.FileName);


                    string[] validExts = { ".jpeg", ".jpg", ".gif", ".png" };


                    if (validExts.Contains(ext.ToLower()) && product.Image.Length < 4_194_303)
                    {


                        product.ProductImage = Guid.NewGuid() + ext;


                        string webRootPath = _webHostEnvironment.WebRootPath;


                        string fullImagePath = webRootPath + "/images/";


                        using (var memoryStream = new MemoryStream())
                        {

                            await product.Image.CopyToAsync(memoryStream);


                            using (var img = Image.FromStream(memoryStream))
                            {


                                int maxImageSize = 500;
                                int maxThumbSize = 100;

                                ImageUtility.ResizeImage(fullImagePath, product.ProductImage, img, maxImageSize, maxThumbSize);


                            }
                        }
                    }
                }
                else
                {

                    product.ProductImage = "noimage.png";
                }


                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["SupplierId"] = new SelectList(_context.ClassLocations, "LocationId", "CampusName", product.LocationId);
            return View(product);

            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["LocationId"] = new SelectList(_context.ClassLocations, "LocationId", "CampusName", product.LocationId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["LocationId"] = new SelectList(_context.ClassLocations, "LocationId", "CampusName", product.LocationId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Price,Discontinued,Description,ProductImage,ProductName,CategoryId,LocationId,IsOnline,Image")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {


                string oldImageName = product.ProductImage;


                if (product.Image != null)
                {

                    string ext = Path.GetExtension(product.Image.FileName);


                    string[] validExts = { ".jpeg", ".jpg", ".gif", ".png" };


                    if (validExts.Contains(ext.ToLower()) && product.Image.Length < 4_194_303)
                    {

                        product.ProductImage = Guid.NewGuid() + ext;


                        string webRootPath = _webHostEnvironment.WebRootPath;
                        string fullImagePath = webRootPath + "/images/";


                        if (oldImageName != "noimage.png")
                        {
                            ImageUtility.Delete(fullImagePath, oldImageName);
                        }


                        using (var memoryStream = new MemoryStream())
                        {

                            await product.Image.CopyToAsync(memoryStream);


                            using (var img = Image.FromStream(memoryStream))
                            {

                                int maxImageSize = 500;
                                int maxThumbSize = 100;


                                ImageUtility.ResizeImage(fullImagePath, product.ProductImage, img, maxImageSize, maxThumbSize);
                            }
                        }
                    }
                }



                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);

StoreFront.UI.MVC/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;

using StoreFront.DATA.EF.Models;
using Microsoft.AspNetCore.Identity;
using StoreFront.UI.MVC.Models;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;

namespace StoreFront.UI.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {


        private readonly EducatedMoneyContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ShoppingCartController(EducatedMoneyContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }




        public IActionResult Index()
        {
            var sessionCart = HttpContext.Session.GetString("cart");

            Dictionary<int, CartItemViewModel> shoppingCart = null;

            if (sessionCart == null || sessionCart.Count() == 0)
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();

                ViewBag.Message = "There are no items in your cart.";
            }
            else
            {
                ViewBag.Message = null;
                shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);
            }


            return View(shoppingCart);
        }



        public IActionResult AddToCart(int id)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            var sessionCart = HttpContext.Session.GetString("cart");

            if (string.IsNullOrEmpty(sessionCart))
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }
            else
            {
                shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);
            }

            Product product = _context.Products.Find(id);

            CartItemViewModel civm = new CartItemViewModel(1, product);

            if (shoppingCart.ContainsKey(product.ProductId))
            {
                shoppingCart[product.ProductId].Qty++;
            }
            else
            {
                shoppingCart.Add(product.ProductId, civm);
            }

            string jsonCart = JsonConvert.SerializeObject(shoppingCart);
            HttpContext.Session.SetString("cart", jsonCart);

            return RedirectToAction("Index");

        }


        public IActionResult RemoveFromCart(int id)
        {
            var sessionCart = HttpContext.Session.GetString("cart");

            Dictionary<int, CartItemViewModel> shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);

            shoppingCart.Remove(id);

            if (shoppingCart.Count == 0)
            {
                HttpContext.Session.Remove("cart");
            }
            else
            {
                string jsonCart = JsonConvert.SerializeObject(shoppingCart);
                HttpContext.Session.SetString("cart", jsonCart);
            }

            return RedirectToAction("Index");
        }


        public IActionResult UpdateCart(int productId, int qty)
        {

            var sessionCart = HttpContext.Session.GetString("cart");


            Dictionary<int, CartItemViewModel> shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);


            if (qty == 0)
            {
                shoppingCart.Remove(productId);

            }
            else
            {
                shoppingCart[productId].Qty = qty;
            }

            string jsonCart = JsonConvert.SerializeObject(shoppingCart);
            HttpContext.Session.SetString("cart", jsonCart);

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> SubmitOrder()
        {
            string? userId = (await _userManager.GetUserAsync(HttpContext.User))?.Id;


            UserDetail ud = _context.UserDetails.Find(userId);


            Order o = new Order()
            {
                PurchaseDate = DateTime.Now,
                UserId = userId
            };


            _context.Orders.Add(o);


            var sessionCart = HttpContext.Session.GetString("cart");


            Dictionary<int, CartItemViewModel> shoppingCart = JsonConvert.DeserializeObject<Dictionary<int, CartItemViewModel>>(sessionCart);


            foreach (var item in shoppingCart)
            {

                o.ProductId = item.Key;
                o.PurchasePrice = item.Value.Product.Price;

                //OrderProduct op = new OrderProduct()
                //{
                //    OrderId = o.OrderId,
                //    ProductId = item.Key,
                //    ProductPrice = item.Value.Product.ProductPrice,
                //    Quantity = (short)item.Value.Qty
                //};


                //o.OrderProducts.Add(op);
            }


            _context.SaveChanges();

            return RedirectToAction("Index", "Orders");

        }

    }//end class
}//end namespace

StoreFront.UI.MVC/Views/ShoppingCart/Index.cshtml
@model Dictionary<int, CartItemViewModel>

@{
    ViewData["Title"] = "Shopping Cart";

    decimal? cartTotal = 0;
}

<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <p>Your Financial Journey Starts Here</p>
                    <h1 class="pb-2">Products</h1>
                    <a asp-action="Index" asp-controller="Products" class="cart-btn"><i class="fas"></i> Back to Shopping</a>
                </div>
            </div>
        </div>
    </div>
</div>

@if (Model.Count == 0)
{
    <p class="alert alert-warning">
        @ViewBag.Message
    </p>
}
else
{
    <!-- cart -->
    <div class="cart-section mt-150 mb-150">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-12">
                    <div class="cart-table-wrap">




                        <table class="cart-table">
                            <thead class="cart-table-head">
                                <tr class="table-head-row">
                                    <th class="product-remove"></th>
                                    <th class="product-image">Product Image</th>
                                    <th class="product-name">Name</th>
                                    <th class="product-price">Price</th>
                                    <th class="product-quantity">Quantity</th>
                                    <th class="product-total">Total</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="table-body-row">
                                        <td class="product-remove">
                                        <a asp-action="RemoveFromCart" asp-controller="ShoppingCart" asp-route-id="@item.Key"> <i class="far fa-window-close"></i></a>
                                        </td>
                                        <td class="product-image"><img src="~/Images/t_@item.Value.Product.ProductImage" alt="@item.Value.Product.ProductName" /></td>

                                        <td class="product-name">@item.Value.Product.ProductName</td>

                                        <td class="product-price">@string.Format($"{item.Value.Product.Price:c}")</td>

                                        <td class="product-quantity">
                                            <form asp-action="UpdateCart">
                                                <input type="hidden" name="productId" value="@item.Key" />
                                                <input type="number" name="qty" value="@item.Value.Qty" class="form-control d-block mx-auto w-50 text-center" />
                                                <input type="submit" value="Update Cart" class="cart-buttons btn-sm" />
                                            </form>
                                        </td>

                                        <td class="product-total">
                                            @{
                                                decimal? lineTotal = item.Value.Product.Price * item.Value.Qty;
                                                cartTotal += lineTotal;
                                            }
                                            @string.Format($"{lineTotal:c}")
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="total-section">
                        <table class="total-table">
                            <thead class="total-table-head">
                                <tr class="table-total-row">
                                    <th>Total</th>
                                    <th>Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="total-data">
                                    <td><strong>Total: </strong></td>
                                    <td>
                                        @string.Format($"{cartTotal:c}").
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="cart-buttons">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a asp-action="SubmitOrder" class="boxed-btn black">Check Out</a>
                            }
                            else
                            {
                            <a href="#" class="boxed-btn black">Sign In To Check Out</a>
                            }
                            @*<a href="cart.html" class="boxed-btn">Update Cart</a>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end cart -->
}